Add logic for getting target based on event name

diff --git a/.github/actions/check-release/action.yml b/.github/actions/check-release/action.yml
--- a/.github/actions/check-release/action.yml
+++ b/.github/actions/check-release/action.yml
@@ -2,8 +2,8 @@ name: Check release
 description: Check for conflicts in packages being released in this PR.
 
 inputs:
-  before:
-    description: 'The commit SHA before the current commit or pull request.'
+  pull-request:
+    description: 'The pull request number to get changed files from.'
     required: true
 
 runs:
@@ -14,10 +14,26 @@ runs:
       with:
         fetch-depth: 0
 
+    - name: Get target reference
+      id: get-target
+      shell: bash
+      env:
+        EVENT_NAME: ${{ github.event_name }}
+      run: |
+        if [ "$EVENT_NAME" = "pull_request" ]; then
+          echo "TARGET=$(git merge-base HEAD main)" >> "$GITHUB_OUTPUT"
+        elif [ "$EVENT_NAME" = "merge_group" ]; then
+          echo "TARGET=$(git rev-parse HEAD^)" >> "$GITHUB_OUTPUT"
+        else
+          echo "::error::This action only supports `pull_request` and `merge_group` events."
+          exit 1
+        fi
+
     - name: Check commits for changes in released packages
       shell: bash
       env:
-        BEFORE: ${{ inputs.before }}
+        PULL_REQUEST: ${{ inputs.pull-request }}
+        TARGET: ${{ steps.get-target.outputs.TARGET }}
       run: |
         set -euo pipefail
         git fetch origin main
@@ -39,20 +55,24 @@ runs:
         done
 
         # Get all files changed ahead of this PR.
-        git diff --name-only "$BEFORE..$MERGE_BASE" > changed-files.txt
+        PULL_REQUEST_BRANCH=$(gh pr view "$PULL_REQUEST" --json headRefName --template "{{ .headRefName }}")
 
-        # Debug info
-        echo "merge-base:"
-        git merge-base HEAD refs/remotes/origin/main
+        echo "🔍 Checking for release conflicts with files changed ahead of PR branch \`$PULL_REQUEST_BRANCH\`..."
 
-        echo "Changed files ahead of this PR:"
-        cat changed-files.txt
+        git fetch origin "$PULL_REQUEST_BRANCH"
+        BEFORE=$(git merge-base "refs/remotes/origin/main" "$PULL_REQUEST_BRANCH")
+
+        # TODO: Remove debug logs
+        echo "Before: $BEFORE"
+        echo "Target: $TARGET"
+
+        git diff --name-only "$BEFORE..$TARGET" > changed-files.txt
 
         CONFLICTS=()
-        for pkg in "${RELEASED_PACKAGES[@]}"; do
-          pkg_dir=$(dirname "$pkg")
-          if grep -q "^$pkg_dir/" changed-files.txt; then
-            CONFLICTS+=("$pkg_dir")
+        for package in "${RELEASED_PACKAGES[@]}"; do
+          package_directory=$(dirname "$package")
+          if grep -q "^$package_directory/" changed-files.txt; then
+            CONFLICTS+=("$package_directory")
           fi
         done
 
